<?php

return [
    'export'          => 'Export',
    'export_csv'      => 'Export CSV',
    'export_excel'    => 'Export Excel',
    'export_pdf'      => 'Export PDF',
    'generating'      => 'Generating…',
    'export_success'  => 'Export completed.',
    'export_error'    => 'Export failed. Please try again.',
    // PDF / report shared labels
    'no'              => 'No.',
    'name'            => 'Name',
    'employee_number' => 'Employee No.',
    'organization'    => 'Organization',
    'position'        => 'Position',
    'status'          => 'Status',
    'date'            => 'Date',
    'amount'          => 'Amount',
    'total'           => 'Total',
    'generated_at'    => 'Generated At',
    'generated_by'    => 'Generated By',
    'page_of'         => 'Page :current of :total',
    'confidential'    => 'Confidential',
    'official_document' => 'Official Document',
];
