import { chromium } from 'playwright';
const OUT = process.env.OUT_DIR;
const b = await chromium.launch({ channel: 'chrome' });
const p = await b.newPage({ viewport: { width: 1440, height: 1000 } });
await p.goto('http://127.0.0.1:8123/login', { waitUntil: 'networkidle' });
await p.fill('input[type="email"]', 'super.admin@demo.local');
await p.fill('input[type="password"]', 'password');
await p.click('button[type="submit"]');
await p.waitForTimeout(4000);
await p.goto('http://127.0.0.1:8123/system-settings/id-card-templates', { waitUntil: 'networkidle' });
await p.waitForTimeout(3500);
console.log('url:', p.url());
await p.screenshot({ path: `${OUT}/tpl-before.png`, fullPage: true });
console.log('captured');
await b.close();
