const exports = {
    export: 'Export',
    exportCsv: 'Export CSV',
    exportExcel: 'Export Excel',
    exportPdf: 'Export PDF',
    exportPng: 'Export PNG',
    print: 'Print',
    printCard: 'Print Card',
    download: 'Download',
    generating: 'Generating…',
    exportSuccess: 'Export completed.',
    exportError: 'Export failed. Please try again.',
    // Column headers shared across reports
    no: 'No.',
    name: 'Name',
    employeeNumber: 'Employee No.',
    organization: 'Organization',
    position: 'Position',
    status: 'Status',
    date: 'Date',
    amount: 'Amount',
    total: 'Total',
    generatedAt: 'Generated At',
    generatedBy: 'Generated By',
    // PDF headers
    reportTitle: 'Report',
    pageOf: 'Page :current of :total',
    confidential: 'Confidential',
    officialDocument: 'Official Document',
} as const;

export default exports;
