const organizationStructureImport = {
    title: 'Import Structure',
    description:
        'Upload one Excel file containing an organization, its units, positions and (optionally) employees.',
    uploadExcelFile: 'Upload Excel File',
    downloadTemplate: 'Download Template',
    previewImport: 'Preview Import',
    confirmImport: 'Confirm Import',
    importErrors: 'Import Errors',
    importWarnings: 'Import Warnings',
    importedSuccessfully: 'Organization Structure Imported Successfully',
    invalidExcelFormat: 'Invalid Excel Format',
    requiredSheetMissing: 'Required sheet missing',
    requiredColumnMissing: 'Required column missing',

    organizationSummary: 'Organization Summary',
    unitTree: 'Organization Unit Structure',
    importSummary: 'Import Summary',
    modeCreate: 'A new organization will be created.',
    modeUpdate: 'The existing organization will be updated.',
    noErrors: 'No errors found. This file is ready to import.',
    errorsBlockImport: 'This file cannot be imported until every error is resolved.',
    reselectFile: 'Select the file again to confirm the import.',
    importEmployees: 'Also import employees and assignments',
    expectedSheets: 'Expected Sheets and Columns',
    required: 'Required',
    optional: 'Optional',

    autoGenerateCodes: 'Auto-generate missing codes',
    autoGenerateHint: 'Leave code fields empty to auto-generate from Code Rules.',
    generatedCodes: 'Generated Codes',
    providedCode: 'Provided Code',
    generatedCode: 'Generated Code',
    codeRuleUsed: 'Code Rule Used',
    generatedByCodeRule: 'Generated by Code Rule',
    name: 'Name',

    counts: {
        units: 'Organization Units',
        positions: 'Positions',
        employees: 'Employees',
    },

    columns: {
        sheet: 'Sheet',
        row: 'Row',
        column: 'Column',
        message: 'Message',
    },
};

export default organizationStructureImport;
