#!/usr/bin/env bash
#
# Builds the `production` branch from a source commit (default: main).
#
# The production branch carries only what the application needs to install,
# build and run on a server. Each run adds ONE commit whose tree is the source
# tree minus the development-only paths below, on top of the previous
# production commit. It never merges, so it never conflicts, and the working
# tree and current branch are left untouched.
#
# Usage:  scripts/release/build-production-branch.sh [source-ref]
# Then:   git push origin production
#
set -euo pipefail

SOURCE_REF="${1:-main}"
TARGET_BRANCH="production"

# Development-only paths. Anything the running application reads must NOT be
# listed here (docs/api-management-guide.md is served by API Management).
EXCLUDE=(
    tests
    phpunit.xml.dist
    phpunit.pgsql.xml.dist
    .github
    .claude
    .agents
    skills-lock.json
    .editorconfig
    docs
    ':!docs/api-management-guide.md'
    TRANSFER_MODULE_GUIDE.md
    external-apps
    employeeId_db
    sec-routes.json
    sec-audit.json
)

cd "$(git rev-parse --show-toplevel)"
source_sha="$(git rev-parse --verify "${SOURCE_REF}^{commit}")"
parent="$(git rev-parse -q --verify "refs/heads/${TARGET_BRANCH}" || true)"

index="$(mktemp)"
trap 'rm -f "$index"' EXIT
export GIT_INDEX_FILE="$index"
git read-tree "$source_sha"
git rm --cached -r -q --ignore-unmatch -- "${EXCLUDE[@]}"
tree="$(git write-tree)"
unset GIT_INDEX_FILE

if [[ -n "$parent" && "$(git rev-parse "${parent}^{tree}")" == "$tree" ]]; then
    echo "${TARGET_BRANCH} already matches ${SOURCE_REF} (${source_sha:0:7}); nothing to do."
    exit 0
fi

message="Production build of ${SOURCE_REF} ${source_sha:0:7}

Source: ${source_sha}
Generated by scripts/release/build-production-branch.sh; do not edit this
branch by hand. Development-only paths are left out (tests, docs, CI and
tooling files, the separate cafeteria app)."

commit="$(git commit-tree "$tree" ${parent:+-p "$parent"} -m "$message")"
git update-ref "refs/heads/${TARGET_BRANCH}" "$commit" ${parent:+"$parent"}

echo "${TARGET_BRANCH} -> ${commit:0:7} (from ${SOURCE_REF} ${source_sha:0:7}); $(git ls-tree -r --name-only "$commit" | wc -l) files."
echo "Publish with: git push origin ${TARGET_BRANCH}"
