import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import PageHeader from '@/Components/PageHeader';
import LocalizedDateDisplay from '@/Components/Calendar/LocalizedDateDisplay';
import { Head, Link, router } from '@inertiajs/react';

type Card = { id: string; employee: string; employee_number: string; card_number: string; status: string; changed_fields: string[]; changed_at: string; can_print: boolean };
export default function ReprintQueue({ cards, labels }: { cards: { data: Card[]; prev_page_url: string | null; next_page_url: string | null }; labels: Record<string, string> & { fields: Record<string, string> } }) {
    return <AuthenticatedLayout header={<PageHeader title={labels.reprint_queue} />}><Head title={labels.reprint_queue} /><div className="overflow-x-auto rounded-xl border bg-white dark:bg-slate-900"><table className="w-full text-left text-sm"><thead><tr>{[labels.fields.full_name, labels.fields.employee_number, labels.card_number, labels.changed_fields, labels.date, labels.status, labels.action].map((label, i) => <th className="p-3" key={i}>{label}</th>)}</tr></thead><tbody>{cards.data.map(card => <tr className="border-t" key={card.id}><td className="p-3">{card.employee}</td><td className="p-3">{card.employee_number}</td><td className="p-3">{card.card_number}</td><td className="p-3">{card.changed_fields.join(', ')}</td><td className="p-3"><LocalizedDateDisplay value={card.changed_at} /></td><td className="p-3">{card.status}</td><td className="space-y-2 p-3"><Link className="block text-blue-700" href={route('id-cards.show', card.id)}>{labels.review}</Link>{card.can_print && <button className="text-blue-700" onClick={() => router.post(route('id-cards.prepare-print', card.id))}>{labels.prepare_print}</button>}</td></tr>)}</tbody></table>{!cards.data.length && <p className="p-5">{labels.empty}</p>}</div><div className="mt-4 flex gap-4">{cards.prev_page_url && <Link href={cards.prev_page_url}>←</Link>}{cards.next_page_url && <Link href={cards.next_page_url}>→</Link>}</div></AuthenticatedLayout>;
}
