<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Grievance Decision Letter — {{ $letterReference }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12pt; color: #1a1a1a; margin: 0; padding: 0; }
        .page { padding: 40px 50px; }
        .header { border-bottom: 2px solid #1e40af; padding-bottom: 16px; margin-bottom: 24px; display: flex; justify-content: space-between; }
        .header h1 { font-size: 14pt; font-weight: bold; color: #1e40af; margin: 0; }
        .ref { font-size: 10pt; color: #4b5563; }
        .section { margin-bottom: 20px; }
        .label { font-size: 9pt; font-weight: bold; color: #6b7280; text-transform: uppercase; letter-spacing: 0.5px; }
        .value { margin-top: 2px; font-size: 11pt; }
        .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 20px; }
        .response-box { border: 1px solid #d1d5db; border-radius: 6px; padding: 16px; background: #f9fafb; margin: 16px 0; }
        .footer { border-top: 1px solid #d1d5db; padding-top: 16px; margin-top: 40px; font-size: 9pt; color: #6b7280; text-align: center; }
        .signature { margin-top: 48px; display: grid; grid-template-columns: 1fr 1fr; gap: 40px; }
        .sig-line { border-top: 1px solid #1a1a1a; padding-top: 4px; font-size: 9pt; }
    </style>
</head>
<body>
    <div class="page">
        <div class="header">
            <div>
                <h1>Addis Ababa City Administration</h1>
                <div style="font-size: 10pt; color: #4b5563;">Employee Unified ID and Service Integration System</div>
                <div style="font-size: 10pt; color: #4b5563; font-style: italic;">አዲስ አበባ ከተማ አስተዳደር — የሠራተኛ አገልግሎት ምላሽ ደብዳቤ</div>
            </div>
            <div style="text-align: right;">
                <div class="label">Reference No.</div>
                <div style="font-family: monospace; font-size: 12pt; font-weight: bold; color: #1e40af;">{{ $letterReference }}</div>
                <div class="ref">Date: {{ $generatedAt->format('d F Y') }}</div>
            </div>
        </div>

        <div class="section">
            <h2 style="font-size: 14pt; font-weight: bold; text-align: center; margin-bottom: 4px;">GRIEVANCE DECISION LETTER</h2>
            <p style="text-align: center; font-size: 10pt; color: #6b7280; margin-top: 0;">
                Re: Grievance Reference — <strong>{{ $grievance->reference_number }}</strong>
            </p>
        </div>

        <div class="grid">
            <div>
                <div class="label">Submitted By</div>
                <div class="value">{{ $grievance->employee?->display_name ?? $grievance->submittedByUser?->name ?? 'N/A' }}</div>
            </div>
            <div>
                <div class="label">Organization</div>
                <div class="value">{{ $grievance->organization?->name_en ?? 'N/A' }}</div>
            </div>
            <div>
                <div class="label">Category</div>
                <div class="value">{{ $grievance->category?->name_en ?? 'N/A' }}</div>
            </div>
            <div>
                <div class="label">Submitted On</div>
                <div class="value">{{ $grievance->submitted_at?->format('d F Y') ?? 'N/A' }}</div>
            </div>
        </div>

        <div class="section">
            <div class="label">Subject</div>
            <div class="value" style="font-weight: bold; font-size: 12pt;">{{ $grievance->subject }}</div>
        </div>

        <div class="section">
            <div class="label">Official Response</div>
            <div class="response-box">
                {!! nl2br(e($response->response_body_en)) !!}
            </div>
            @if($response->response_body_am)
            <div class="response-box" style="margin-top: 8px;">
                {!! nl2br(e($response->response_body_am)) !!}
            </div>
            @endif
        </div>

        <div class="signature">
            <div>
                <div class="sig-line">Chairperson Signature &amp; Date</div>
            </div>
            <div>
                <div class="sig-line">Authorized Manager Signature &amp; Date</div>
            </div>
        </div>

        <div class="footer">
            This is an official decision letter generated by the EUISIS Grievance Management System.<br>
            Document Reference: {{ $letterReference }} &mdash; Generated: {{ $generatedAt->toIso8601String() }}
        </div>
    </div>
</body>
</html>
