<?php

declare(strict_types=1);

namespace App\Http\Requests;

use App\Models\Organization;
use Illuminate\Foundation\Http\FormRequest;

/**
 * The confirm step re-uploads the same file rather than referencing a cached
 * preview: the workbook is re-read and re-validated from scratch before any
 * write, so a file that has gone stale since the preview cannot slip through.
 */
class ConfirmOrganizationStructureImportRequest extends FormRequest
{
    public function authorize(): bool
    {
        $user = $this->user();

        return $user !== null && $user->can('import', Organization::class);
    }

    protected function prepareForValidation(): void
    {
        // Employees are imported and blank codes generated by default; the
        // wizard may opt out of either explicitly.
        $this->merge([
            'import_employees' => $this->has('import_employees')
                ? $this->boolean('import_employees')
                : true,
            'auto_generate_codes' => $this->has('auto_generate_codes')
                ? $this->boolean('auto_generate_codes')
                : true,
        ]);
    }

    public function rules(): array
    {
        return [
            'file' => ['required', 'file', 'mimes:xlsx,xls,csv', 'max:10240'],
            'import_employees' => ['boolean'],
            'auto_generate_codes' => ['boolean'],
        ];
    }

    public function messages(): array
    {
        return [
            'file.mimes' => __('organization-structure-import.errors.invalid_excel_format'),
        ];
    }
}
