<?php

declare(strict_types=1);

namespace App\Services\CodeGeneration;

class CodeFormatTokenRegistry
{
    /**
     * @return array<string, array{
     *     token: string,
     *     label_en: string,
     *     label_am: string,
     *     description_en: string,
     *     description_am: string,
     *     category: string,
     *     requires_context: bool,
     *     context_key: string|null,
     *     example: string,
     *     is_active: bool,
     *     supported_entity_types: array<string>|null,
     * }>
     */
    public function all(): array
    {
        return [
            // ── CORE ──────────────────────────────────────────────────────────
            'PREFIX' => [
                'token' => 'PREFIX',
                'label_en' => 'Prefix',
                'label_am' => 'ቅድመ ኮድ',
                'description_en' => 'Inserts the configured prefix value.',
                'description_am' => 'የተዘጋጀውን ቅድመ ኮድ ያስገባል።',
                'category' => 'Core',
                'requires_context' => false,
                'context_key' => null,
                'example' => 'ORG',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'SUFFIX' => [
                'token' => 'SUFFIX',
                'label_en' => 'Suffix',
                'label_am' => 'ተከታይ ኮድ',
                'description_en' => 'Inserts the configured suffix value.',
                'description_am' => 'የተዘጋጀውን ተከታይ ኮድ ያስገባል።',
                'category' => 'Core',
                'requires_context' => false,
                'context_key' => null,
                'example' => 'AA',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'SEPARATOR' => [
                'token' => 'SEPARATOR',
                'label_en' => 'Separator',
                'label_am' => 'መለያ ምልክት',
                'description_en' => 'Inserts the configured separator character.',
                'description_am' => 'የተዘጋጀውን መለያ ምልክት ያስገባል።',
                'category' => 'Core',
                'requires_context' => false,
                'context_key' => null,
                'example' => '-',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'SEQUENCE' => [
                'token' => 'SEQUENCE',
                'label_en' => 'Sequence',
                'label_am' => 'ተከታታይ ቁጥር',
                'description_en' => 'Inserts the next sequence number (zero-padded to sequence_length).',
                'description_am' => 'ቀጣዩን ተከታታይ ቁጥር ያስገባል (እስከ sequence_length ርዝመት ዜሮ ይሞላል)።',
                'category' => 'Core',
                'requires_context' => false,
                'context_key' => null,
                'example' => '0001',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'SEQUENCE_PADDED' => [
                'token' => 'SEQUENCE_PADDED',
                'label_en' => 'Sequence (Padded)',
                'label_am' => 'ተከታታይ ቁጥር (ዜሮ ሞልቶ)',
                'description_en' => 'Inserts the next sequence number padded with leading zeros to sequence_length.',
                'description_am' => 'ቀጣዩን ተከታታይ ቁጥር በቀዳሚ ዜሮዎች ሞልቶ ያስገባል።',
                'category' => 'Core',
                'requires_context' => false,
                'context_key' => null,
                'example' => '00001',
                'is_active' => true,
                'supported_entity_types' => null,
            ],

            // ── DATE / TIME ───────────────────────────────────────────────────
            'YEAR' => [
                'token' => 'YEAR',
                'label_en' => 'Year (4-digit)',
                'label_am' => 'ዓመት (4 አሃዝ)',
                'description_en' => 'Inserts the current 4-digit year (e.g. 2026).',
                'description_am' => 'አሁን ያለውን 4 አሃዝ ዓመት ያስገባል።',
                'category' => 'DateAndTime',
                'requires_context' => false,
                'context_key' => null,
                'example' => '2026',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'YEAR_SHORT' => [
                'token' => 'YEAR_SHORT',
                'label_en' => 'Year (2-digit)',
                'label_am' => 'ዓመት (2 አሃዝ)',
                'description_en' => 'Inserts the current 2-digit year (e.g. 26).',
                'description_am' => 'አሁን ያለውን 2 አሃዝ ዓመት ያስገባል።',
                'category' => 'DateAndTime',
                'requires_context' => false,
                'context_key' => null,
                'example' => '26',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'MONTH' => [
                'token' => 'MONTH',
                'label_en' => 'Month (numeric)',
                'label_am' => 'ወር (ቁጥር)',
                'description_en' => 'Inserts the current month as a 2-digit number (01–12).',
                'description_am' => 'አሁን ያለውን ወር እንደ 2 አሃዝ ቁጥር ያስገባል።',
                'category' => 'DateAndTime',
                'requires_context' => false,
                'context_key' => null,
                'example' => '05',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'MONTH_NAME' => [
                'token' => 'MONTH_NAME',
                'label_en' => 'Month (name)',
                'label_am' => 'ወር (ስም)',
                'description_en' => 'Inserts the current month name in uppercase (e.g. MAY).',
                'description_am' => 'አሁን ያለውን የወር ስም በካፒታል ፊደል ያስገባል።',
                'category' => 'DateAndTime',
                'requires_context' => false,
                'context_key' => null,
                'example' => 'MAY',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'DAY' => [
                'token' => 'DAY',
                'label_en' => 'Day',
                'label_am' => 'ቀን',
                'description_en' => 'Inserts the current day of month as a 2-digit number (01–31).',
                'description_am' => 'አሁን ያለውን የወሩ ቀን እንደ 2 አሃዝ ቁጥር ያስገባል።',
                'category' => 'DateAndTime',
                'requires_context' => false,
                'context_key' => null,
                'example' => '14',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'DATE' => [
                'token' => 'DATE',
                'label_en' => 'Date (YYYYMMDD)',
                'label_am' => 'ቀን (YYYYMMDD)',
                'description_en' => 'Inserts the current date in YYYYMMDD format.',
                'description_am' => 'አሁን ያለውን ቀን በ YYYYMMDD ቅርጸት ያስገባል።',
                'category' => 'DateAndTime',
                'requires_context' => false,
                'context_key' => null,
                'example' => '20260514',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'TIME' => [
                'token' => 'TIME',
                'label_en' => 'Time (HHmmss)',
                'label_am' => 'ሰዓት (HHmmss)',
                'description_en' => 'Inserts the current time in HHmmss format.',
                'description_am' => 'አሁን ያለውን ሰዓት በ HHmmss ቅርጸት ያስገባል።',
                'category' => 'DateAndTime',
                'requires_context' => false,
                'context_key' => null,
                'example' => '093045',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'TIMESTAMP' => [
                'token' => 'TIMESTAMP',
                'label_en' => 'Timestamp (YYYYMMDDHHmmss)',
                'label_am' => 'ጊዜ ምልክት (YYYYMMDDHHmmss)',
                'description_en' => 'Inserts the current date and time in YYYYMMDDHHmmss format.',
                'description_am' => 'አሁን ያለውን ቀን እና ሰዓት ያስገባል።',
                'category' => 'DateAndTime',
                'requires_context' => false,
                'context_key' => null,
                'example' => '20260514093045',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'FISCAL_YEAR' => [
                'token' => 'FISCAL_YEAR',
                'label_en' => 'Fiscal Year',
                'label_am' => 'የበጀት ዓመት',
                'description_en' => 'Inserts the current fiscal year (approximated as the Gregorian year).',
                'description_am' => 'አሁን ያለውን የበጀት ዓመት ያስገባል (ቀደምት ቀረጻ ዓ.ም. ነው)።',
                'category' => 'DateAndTime',
                'requires_context' => false,
                'context_key' => null,
                'example' => '2026',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'ETHIOPIAN_YEAR' => [
                'token' => 'ETHIOPIAN_YEAR',
                'label_en' => 'Ethiopian Year',
                'label_am' => 'የኢትዮጵያ ዓመት',
                'description_en' => 'Inserts the current Ethiopian calendar year (future placeholder — not yet active).',
                'description_am' => 'አሁን ያለውን የኢትዮጵያ ቀን አቆጣጠር ዓመት ያስገባል (ወደፊት ይተዋወቃል)።',
                'category' => 'DateAndTime',
                'requires_context' => false,
                'context_key' => null,
                'example' => '2018',
                'is_active' => false,
                'supported_entity_types' => null,
            ],

            // ── ORGANIZATION ──────────────────────────────────────────────────
            'ORG_CODE' => [
                'token' => 'ORG_CODE',
                'label_en' => 'Organization Code',
                'label_am' => 'የድርጅት ኮድ',
                'description_en' => 'Inserts the code of the organization from context.',
                'description_am' => 'ከዓውድ ያለውን የድርጅት ኮድ ያስገባል።',
                'category' => 'Organization',
                'requires_context' => true,
                'context_key' => 'organization_id',
                'example' => 'BUR-PSHRDB',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'ORG_PREFIX' => [
                'token' => 'ORG_PREFIX',
                'label_en' => 'Organization Prefix',
                'label_am' => 'የድርጅት ቅድመ ኮድ',
                'description_en' => 'Inserts the prefix of the organization (falls back to org type prefix, then first 3 letters of code).',
                'description_am' => 'የድርጅቱን ቅድመ ኮድ ያስገባል (ካልተገኘ የዓይነቱን ወይም የኮዱን ቀዳሚ ፊደሎች ይጠቀማል)።',
                'category' => 'Organization',
                'requires_context' => true,
                'context_key' => 'organization_id',
                'example' => 'BUR',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'ORG_NAME' => [
                'token' => 'ORG_NAME',
                'label_en' => 'Organization Name',
                'label_am' => 'የድርጅት ስም',
                'description_en' => 'Inserts the sanitized uppercase English name of the organization.',
                'description_am' => 'የድርጅቱን ስም (እንግሊዝኛ) በካፒታል ፊደሎች ያስገባል።',
                'category' => 'Organization',
                'requires_context' => true,
                'context_key' => 'organization_id',
                'example' => 'PUBLICSERVICEBUREAU',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'ORG_TYPE_CODE' => [
                'token' => 'ORG_TYPE_CODE',
                'label_en' => 'Organization Type Code',
                'label_am' => 'የድርጅት ዓይነት ኮድ',
                'description_en' => 'Inserts the code of the organization type from context.',
                'description_am' => 'ከዓውድ ያለውን የድርጅት ዓይነት ኮድ ያስገባል።',
                'category' => 'Organization',
                'requires_context' => true,
                'context_key' => 'organization_id',
                'example' => 'BUREAU',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'ORG_TYPE_PREFIX' => [
                'token' => 'ORG_TYPE_PREFIX',
                'label_en' => 'Organization Type Prefix',
                'label_am' => 'የድርጅት ዓይነት ቅድመ ኮድ',
                'description_en' => 'Inserts the prefix of the organization type (falls back to type code).',
                'description_am' => 'የድርጅት ዓይነቱን ቅድመ ኮድ ያስገባል (ካልተገኘ ዓይነቱን ኮድ ይጠቀማል)።',
                'category' => 'Organization',
                'requires_context' => true,
                'context_key' => 'organization_id',
                'example' => 'BUR',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'ORG_TYPE_NAME' => [
                'token' => 'ORG_TYPE_NAME',
                'label_en' => 'Organization Type Name',
                'label_am' => 'የድርጅት ዓይነት ስም',
                'description_en' => 'Inserts the sanitized uppercase English name of the organization type.',
                'description_am' => 'የድርጅት ዓይነቱን ስም (እንግሊዝኛ) በካፒታል ፊደሎች ያስገባል።',
                'category' => 'Organization',
                'requires_context' => true,
                'context_key' => 'organization_id',
                'example' => 'BUREAU',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'PARENT_ORG_CODE' => [
                'token' => 'PARENT_ORG_CODE',
                'label_en' => 'Parent Organization Code',
                'label_am' => 'የወላጅ ድርጅት ኮድ',
                'description_en' => 'Inserts the code of the parent organization.',
                'description_am' => 'የወላጅ ድርጅቱን ኮድ ያስገባል።',
                'category' => 'Organization',
                'requires_context' => true,
                'context_key' => 'parent_organization_id',
                'example' => 'AA-ROOT',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'PARENT_ORG_PREFIX' => [
                'token' => 'PARENT_ORG_PREFIX',
                'label_en' => 'Parent Organization Prefix',
                'label_am' => 'የወላጅ ድርጅት ቅድመ ኮድ',
                'description_en' => 'Inserts the prefix of the parent organization.',
                'description_am' => 'የወላጅ ድርጅቱን ቅድመ ኮድ ያስገባል።',
                'category' => 'Organization',
                'requires_context' => true,
                'context_key' => 'parent_organization_id',
                'example' => 'CITY',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'UNIT_CODE' => [
                'token' => 'UNIT_CODE',
                'label_en' => 'Organization Unit Code',
                'label_am' => 'የድርጅት ዩኒት ኮድ',
                'description_en' => 'Inserts the code of the organization unit from context.',
                'description_am' => 'ከዓውድ ያለውን የድርጅት ዩኒት ኮድ ያስገባል።',
                'category' => 'Organization',
                'requires_context' => true,
                'context_key' => 'organization_unit_id',
                'example' => 'UNIT-001',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'UNIT_TYPE_CODE' => [
                'token' => 'UNIT_TYPE_CODE',
                'label_en' => 'Organization Unit Type Code',
                'label_am' => 'የድርጅት ዩኒት ዓይነት ኮድ',
                'description_en' => 'Inserts the code of the organization unit type.',
                'description_am' => 'የድርጅት ዩኒት ዓይነቱን ኮድ ያስገባል።',
                'category' => 'Organization',
                'requires_context' => true,
                'context_key' => 'organization_unit_id',
                'example' => 'DEPT',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'UNIT_PREFIX' => [
                'token' => 'UNIT_PREFIX',
                'label_en' => 'Organization Unit Prefix',
                'label_am' => 'የድርጅት ዩኒት ቅድመ ኮድ',
                'description_en' => 'Inserts the prefix of the organization unit type (falls back to first letters of unit code).',
                'description_am' => 'የድርጅት ዩኒት ዓይነቱን ቅድመ ኮድ ያስገባል።',
                'category' => 'Organization',
                'requires_context' => true,
                'context_key' => 'organization_unit_id',
                'example' => 'DEPT',
                'is_active' => true,
                'supported_entity_types' => null,
            ],

            // ── EMPLOYEE ──────────────────────────────────────────────────────
            'EMPLOYEE_NUMBER' => [
                'token' => 'EMPLOYEE_NUMBER',
                'label_en' => 'Employee Number',
                'label_am' => 'የሰራተኛ ቁጥር',
                'description_en' => 'Inserts the employee number from context.',
                'description_am' => 'ከዓውድ ያለውን የሰራተኛ ቁጥር ያስገባል።',
                'category' => 'Employee',
                'requires_context' => true,
                'context_key' => 'employee_id',
                'example' => 'EMP-2026-000001',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'EMPLOYEE_INITIALS' => [
                'token' => 'EMPLOYEE_INITIALS',
                'label_en' => 'Employee Initials',
                'label_am' => 'የሰራተኛ ቀዳሚ ፊደሎች',
                'description_en' => 'Inserts the initials extracted from the employee name.',
                'description_am' => 'ከሰራተኛው ስም የተወሰዱ ቀዳሚ ፊደሎችን ያስገባል።',
                'category' => 'Employee',
                'requires_context' => true,
                'context_key' => 'employee_id',
                'example' => 'AB',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'EMPLOYEE_STATUS' => [
                'token' => 'EMPLOYEE_STATUS',
                'label_en' => 'Employee Status',
                'label_am' => 'የሰራተኛ ሁኔታ',
                'description_en' => 'Inserts the employee status in uppercase.',
                'description_am' => 'የሰራተኛውን ሁኔታ በካፒታል ፊደሎች ያስገባል።',
                'category' => 'Employee',
                'requires_context' => true,
                'context_key' => 'employee_id',
                'example' => 'ACTIVE',
                'is_active' => true,
                'supported_entity_types' => null,
            ],

            // ── POSITION ──────────────────────────────────────────────────────
            'POSITION_CODE' => [
                'token' => 'POSITION_CODE',
                'label_en' => 'Position Code',
                'label_am' => 'የስራ መደብ ኮድ',
                'description_en' => 'Inserts the position code (job_position_code or code field).',
                'description_am' => 'የስራ መደቡን ኮድ ያስገባል።',
                'category' => 'Position',
                'requires_context' => true,
                'context_key' => 'position_id',
                'example' => 'POS-0001',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'JOB_POSITION_CODE' => [
                'token' => 'JOB_POSITION_CODE',
                'label_en' => 'Job Position Code',
                'label_am' => 'የስራ መደብ ኮድ',
                'description_en' => 'Alias for POSITION_CODE — inserts the job position code.',
                'description_am' => 'የ POSITION_CODE አቻ — የስራ መደቡን ኮድ ያስገባል።',
                'category' => 'Position',
                'requires_context' => true,
                'context_key' => 'position_id',
                'example' => 'POS-0001',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'POSITION_PREFIX' => [
                'token' => 'POSITION_PREFIX',
                'label_en' => 'Position Prefix',
                'label_am' => 'የስራ መደብ ቅድመ ኮድ',
                'description_en' => 'Inserts the prefix of the position (falls back to first letters of position code).',
                'description_am' => 'የስራ መደቡን ቅድመ ኮድ ያስገባል።',
                'category' => 'Position',
                'requires_context' => true,
                'context_key' => 'position_id',
                'example' => 'POS',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'POSITION_TITLE' => [
                'token' => 'POSITION_TITLE',
                'label_en' => 'Position Title',
                'label_am' => 'የስራ መደብ ርዕስ',
                'description_en' => 'Inserts the sanitized uppercase English title of the position.',
                'description_am' => 'የስራ መደቡን ርዕስ (እንግሊዝኛ) በካፒታል ፊደሎች ያስገባል።',
                'category' => 'Position',
                'requires_context' => true,
                'context_key' => 'position_id',
                'example' => 'HROFFICER',
                'is_active' => true,
                'supported_entity_types' => null,
            ],

            // ── SERVICE ───────────────────────────────────────────────────────
            'SERVICE_TYPE_CODE' => [
                'token' => 'SERVICE_TYPE_CODE',
                'label_en' => 'Service Type Code',
                'label_am' => 'የአገልግሎት ዓይነት ኮድ',
                'description_en' => 'Inserts the code of the service type from context.',
                'description_am' => 'ከዓውድ ያለውን የአገልግሎት ዓይነት ኮድ ያስገባል።',
                'category' => 'Service',
                'requires_context' => true,
                'context_key' => 'service_type_id',
                'example' => 'TRANSPORT',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'SERVICE_TYPE_PREFIX' => [
                'token' => 'SERVICE_TYPE_PREFIX',
                'label_en' => 'Service Type Prefix',
                'label_am' => 'የአገልግሎት ዓይነት ቅድመ ኮድ',
                'description_en' => 'Inserts the prefix of the service type (falls back to first letters of type code).',
                'description_am' => 'የአገልግሎት ዓይነቱን ቅድመ ኮድ ያስገባል።',
                'category' => 'Service',
                'requires_context' => true,
                'context_key' => 'service_type_id',
                'example' => 'TRN',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'PROVIDER_CODE' => [
                'token' => 'PROVIDER_CODE',
                'label_en' => 'Service Provider Code',
                'label_am' => 'የአገልግሎት አቅራቢ ኮድ',
                'description_en' => 'Inserts the code of the service provider from context.',
                'description_am' => 'ከዓውድ ያለውን የአገልግሎት አቅራቢ ኮድ ያስገባል።',
                'category' => 'Service',
                'requires_context' => true,
                'context_key' => 'service_provider_id',
                'example' => 'SP-TRANSPORT-01',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'PROVIDER_PREFIX' => [
                'token' => 'PROVIDER_PREFIX',
                'label_en' => 'Service Provider Prefix',
                'label_am' => 'የአገልግሎት አቅራቢ ቅድመ ኮድ',
                'description_en' => 'Inserts the prefix of the service provider (falls back to first letters of provider code).',
                'description_am' => 'የአገልግሎት አቅራቢውን ቅድመ ኮድ ያስገባል።',
                'category' => 'Service',
                'requires_context' => true,
                'context_key' => 'service_provider_id',
                'example' => 'SP',
                'is_active' => true,
                'supported_entity_types' => null,
            ],

            // ── LOCATION ──────────────────────────────────────────────────────
            'CITY_CODE' => [
                'token' => 'CITY_CODE',
                'label_en' => 'City Code',
                'label_am' => 'የከተማ ኮድ',
                'description_en' => 'Inserts the city code from context.',
                'description_am' => 'ከዓውድ ያለውን የከተማ ኮድ ያስገባል።',
                'category' => 'Location',
                'requires_context' => true,
                'context_key' => 'city_code',
                'example' => 'AA',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'SUB_CITY_CODE' => [
                'token' => 'SUB_CITY_CODE',
                'label_en' => 'Sub-city Code',
                'label_am' => 'የክፍለ ከተማ ኮድ',
                'description_en' => 'Inserts the sub-city code from context.',
                'description_am' => 'ከዓውድ ያለውን የክፍለ ከተማ ኮድ ያስገባል።',
                'category' => 'Location',
                'requires_context' => true,
                'context_key' => 'sub_city_code',
                'example' => 'SC-01',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'WOREDA_CODE' => [
                'token' => 'WOREDA_CODE',
                'label_en' => 'Woreda Code',
                'label_am' => 'የወረዳ ኮድ',
                'description_en' => 'Inserts the woreda code from context.',
                'description_am' => 'ከዓውድ ያለውን የወረዳ ኮድ ያስገባል።',
                'category' => 'Location',
                'requires_context' => true,
                'context_key' => 'woreda_code',
                'example' => 'WRD-01',
                'is_active' => true,
                'supported_entity_types' => null,
            ],

            // ── WORKFLOW ──────────────────────────────────────────────────────
            'REQUEST_TYPE' => [
                'token' => 'REQUEST_TYPE',
                'label_en' => 'Request Type',
                'label_am' => 'የጥያቄ ዓይነት',
                'description_en' => 'Inserts the sanitized request type from context.',
                'description_am' => 'ከዓውድ ያለውን የጥያቄ ዓይነት ያስገባል።',
                'category' => 'Workflow',
                'requires_context' => true,
                'context_key' => 'request_type',
                'example' => 'NEW',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'WORKFLOW_CODE' => [
                'token' => 'WORKFLOW_CODE',
                'label_en' => 'Workflow Code',
                'label_am' => 'የስራ ሂደት ኮድ',
                'description_en' => 'Inserts the workflow code from context.',
                'description_am' => 'ከዓውድ ያለውን የስራ ሂደት ኮድ ያስገባል።',
                'category' => 'Workflow',
                'requires_context' => true,
                'context_key' => 'workflow_code',
                'example' => 'WF-CARD',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'APPROVAL_STEP_CODE' => [
                'token' => 'APPROVAL_STEP_CODE',
                'label_en' => 'Approval Step Code',
                'label_am' => 'የፈቃድ ደረጃ ኮድ',
                'description_en' => 'Inserts the approval step code from context.',
                'description_am' => 'ከዓውድ ያለውን የፈቃድ ደረጃ ኮድ ያስገባል።',
                'category' => 'Workflow',
                'requires_context' => true,
                'context_key' => 'approval_step_code',
                'example' => 'STEP-01',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'DOCUMENT_TYPE_CODE' => [
                'token' => 'DOCUMENT_TYPE_CODE',
                'label_en' => 'Document Type Code',
                'label_am' => 'የሰነድ ዓይነት ኮድ',
                'description_en' => 'Inserts the sanitized document type code from context.',
                'description_am' => 'ከዓውድ ያለውን የሰነድ ዓይነት ኮድ ያስገባል።',
                'category' => 'Workflow',
                'requires_context' => true,
                'context_key' => 'document_type_code',
                'example' => 'CONTRACT',
                'is_active' => true,
                'supported_entity_types' => null,
            ],

            // ── CUSTOM ────────────────────────────────────────────────────────
            'CUSTOM' => [
                'token' => 'CUSTOM',
                'label_en' => 'Custom Value',
                'label_am' => 'ብጁ እሴት',
                'description_en' => 'Inserts a custom value passed directly in context.',
                'description_am' => 'ከዓውድ ቀጥታ የሚላከውን ብጁ እሴት ያስገባል።',
                'category' => 'Custom',
                'requires_context' => false,
                'context_key' => 'custom',
                'example' => 'CUSTOM1',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'CUSTOM_1' => [
                'token' => 'CUSTOM_1',
                'label_en' => 'Custom Value 1',
                'label_am' => 'ብጁ እሴት 1',
                'description_en' => 'Inserts the first custom value passed in context.',
                'description_am' => 'ከዓውድ የሚላከውን የመጀመሪያ ብጁ እሴት ያስገባል።',
                'category' => 'Custom',
                'requires_context' => false,
                'context_key' => 'custom_1',
                'example' => 'CUSTOM1',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'CUSTOM_2' => [
                'token' => 'CUSTOM_2',
                'label_en' => 'Custom Value 2',
                'label_am' => 'ብጁ እሴት 2',
                'description_en' => 'Inserts the second custom value passed in context.',
                'description_am' => 'ከዓውድ የሚላከውን ሁለተኛ ብጁ እሴት ያስገባል።',
                'category' => 'Custom',
                'requires_context' => false,
                'context_key' => 'custom_2',
                'example' => 'CUSTOM2',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
            'CUSTOM_3' => [
                'token' => 'CUSTOM_3',
                'label_en' => 'Custom Value 3',
                'label_am' => 'ብጁ እሴት 3',
                'description_en' => 'Inserts the third custom value passed in context.',
                'description_am' => 'ከዓውድ የሚላከውን ሦስተኛ ብጁ እሴት ያስገባል።',
                'category' => 'Custom',
                'requires_context' => false,
                'context_key' => 'custom_3',
                'example' => 'CUSTOM3',
                'is_active' => true,
                'supported_entity_types' => null,
            ],
        ];
    }

    /**
     * Return only active tokens.
     *
     * @return array<string, array{token: string, label_en: string, label_am: string, description_en: string, description_am: string, category: string, requires_context: bool, context_key: string|null, example: string, is_active: bool, supported_entity_types: array<string>|null}>
     */
    public function active(): array
    {
        return array_filter($this->all(), static fn (array $token): bool => $token['is_active']);
    }

    /**
     * Check whether a token key exists in the registry.
     */
    public function has(string $tokenKey): bool
    {
        return array_key_exists($tokenKey, $this->all());
    }

    /**
     * Check whether a token key is active.
     */
    public function isActive(string $tokenKey): bool
    {
        return ($this->all()[$tokenKey]['is_active'] ?? false) === true;
    }

    /**
     * Return a minimal payload suitable for the frontend (label/category/example only).
     *
     * @return list<array{token: string, label_en: string, label_am: string, description_en: string, description_am: string, category: string, requires_context: bool, example: string, is_active: bool}>
     */
    public function forFrontend(bool $activeOnly = true): array
    {
        $tokens = $activeOnly ? $this->active() : $this->all();

        return array_values(array_map(
            static fn (array $t): array => [
                'token' => $t['token'],
                'label_en' => $t['label_en'],
                'label_am' => $t['label_am'],
                'description_en' => $t['description_en'],
                'description_am' => $t['description_am'],
                'category' => $t['category'],
                'requires_context' => $t['requires_context'],
                'example' => $t['example'],
                'is_active' => $t['is_active'],
            ],
            $tokens,
        ));
    }
}
