import { Link } from '@inertiajs/react';
import { useLocale } from '@/hooks/useLocale';
import { ActionForm, CaseBanner, Timeline, Workspace } from '@/Components/grievances/Workspace';
import { Section, GPill, nameOf, primaryBtn, secondaryBtn, useEnumLabel, fileSize } from '@/Components/grievances/ui';
import DateDisplay from '@/Components/Calendar/LocalizedDateDisplay';
import type { PortalShowProps } from '@/types/grievances';

export default function Show({ grievance: g, can, appeal, reasonCodes, evidenceTypes }: PortalShowProps) {
    const { t, locale } = useLocale(); const label = useEnumLabel();
    const url = (action: string) => route(`employee.grievances.${action}`, g.id);
    return <Workspace portal title={g.subject ?? g.reference_number} backHref={route('employee.grievances.index')} actions={can.edit && <Link className={secondaryBtn} href={url('edit')}>{t('grievances.common.edit')}</Link>}>
        <CaseBanner grievance={g} />
        <Section title={t('grievancePortal.details')}><p className="whitespace-pre-wrap">{g.description}</p><p className="mt-3">{t('grievances.common.incident_date')}: <DateDisplay value={g.incident_date} /></p>{g.respondent_description && <p className="mt-3 whitespace-pre-wrap">{g.respondent_description}</p>}{can.submit && <ActionForm url={url('submit')} title={t('grievancePortal.submit')} />}</Section>
        <Section title={t('grievancePortal.information')}>{g.information_requests.map(r => <div className="mb-4 space-y-3 border-b pb-4" key={r.id}><p className="whitespace-pre-wrap font-medium">{r.request_text}</p><GPill group="information_status" value={r.status} /><DateDisplay value={r.due_at} />{r.responses.map((a, i) => <p key={i} className="whitespace-pre-wrap">{a.response_text} <DateDisplay value={a.responded_at} /></p>)}{r.status === 'open' && <ActionForm url={route('employee.grievances.information.respond', [g.id, r.id])} title={t('grievancePortal.respond')} fields={[{ name: 'response_text', label: t('grievancePortal.response'), type: 'textarea', required: true }, { name: 'files', label: t('grievances.common.files'), type: 'file', multiple: true }]} />}</div>)}</Section>
        <Section title={t('grievancePortal.evidence')}><div className="space-y-3">{g.evidence.map(e => <div key={e.id} className="flex flex-wrap items-center gap-3"><a className="text-blue-700 underline" href={route('employee.grievances.evidence.download', [g.id, e.id])}>{e.title}</a><span>{fileSize(e.size_bytes)}</span><GPill group="evidence_status" value={e.status} /></div>)}</div>{can.upload && <div className="mt-4"><ActionForm url={url('evidence.store')} title={t('grievances.common.upload')} fields={[{ name: 'title', label: t('grievances.common.subject'), required: true }, { name: 'evidence_type', label: t('grievances.common.type'), type: 'select', required: true, options: evidenceTypes.map(v => ({ value: v, label: label('evidence_type', v) })) }, { name: 'file', label: t('grievances.common.file'), type: 'file', required: true }, { name: 'description', label: t('grievances.common.description'), type: 'textarea' }]} /></div>}</Section>
        <Section title={t('grievancePortal.letters')}>{g.letters.map(l => <div key={l.id} className="flex items-center justify-between border-b py-3"><div><p>{l.subject}</p><span className="text-sm">{l.reference_number} · <DateDisplay value={l.issued_at} /></span></div><a className={primaryBtn} href={route('employee.grievances.letters.download', [g.id, l.id])}>{t('grievances.common.download')}</a></div>)}</Section>
        {(can.accept_outcome || can.appeal || g.appeals.length > 0 || appeal.reason) && <Section title={t('grievancePortal.outcome')}><p className="mb-3">{t('grievances.common.appeal_deadline')}: <DateDisplay value={appeal.deadline} /></p>{appeal.reason && <p className="mb-3">{appeal.reason}</p>}{can.appeal && <ActionForm url={url('appeal')} title={t('grievancePortal.appeal')} fields={[{ name: 'reason', label: t('grievances.common.reason'), type: 'textarea', required: true }, { name: 'files', label: t('grievances.common.files'), type: 'file', multiple: true }]} />}{can.accept_outcome && <div className="mt-4"><ActionForm url={url('accept-outcome')} title={t('grievancePortal.accept')}><p className="text-sm">{t('grievancePortal.accept_help')}</p></ActionForm></div>}{g.appeals.map(a => <p key={a.id} className="mt-4"><GPill group="appeal_status" value={a.status} /> <DateDisplay value={a.filed_at} /> {a.reason}</p>)}</Section>}
        <Section title={t('grievancePortal.timeline')}><Timeline events={g.timeline} /></Section>
        {can.withdraw && <Section title={t('grievancePortal.withdraw')}><ActionForm url={url('withdraw')} title={t('grievancePortal.withdraw')} fields={[{ name: 'reason_code', label: t('grievances.common.reason_code'), type: 'select', required: true, options: reasonCodes.map(r => ({ value: r.code, label: nameOf(r, locale) })) }, { name: 'reason', label: t('grievances.common.notes'), type: 'textarea' }]} /></Section>}
        {can.delete && <Section title={t('grievancePortal.delete_draft')}><ActionForm url={url('destroy')} method="delete" title={t('grievancePortal.delete_draft')}><p>{t('grievancePortal.delete_help')}</p></ActionForm></Section>}
    </Workspace>;
}
