<?php

declare(strict_types=1);

use App\Enums\AssignmentStatus;
use App\Enums\CodeRuleEntityType;
use App\Enums\CodeRuleResetFrequency;
use App\Enums\CodeRuleScopeStrategy;
use App\Enums\EmployeeStatus;
use App\Enums\OrganizationStatus;
use App\Enums\OrganizationUnitStatus;
use App\Models\CodeRule;
use App\Models\Employee;
use App\Models\EmployeeAssignment;
use App\Models\Organization;
use App\Models\OrganizationType;
use App\Models\OrganizationUnit;
use App\Models\Position;
use App\Models\User;
use Inertia\Testing\AssertableInertia as Assert;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

/**
 * Employees/Create — authorization, dependent-option filtering (only active
 * organizations/units and active, vacant positions may be used), and required
 * validation. The backend stays the source of truth: even if the UI were
 * bypassed, an inactive or occupied placement must be rejected.
 */
beforeEach(function (): void {
    foreach (['employees.view', 'employees.manage'] as $perm) {
        Permission::findOrCreate($perm, 'web');
    }

    Role::findOrCreate('EC Manager', 'web')->givePermissionTo(['employees.view', 'employees.manage']);
    Role::findOrCreate('EC Viewer', 'web')->givePermissionTo(['employees.view']);

    $this->ecType = OrganizationType::query()->create([
        'code' => 'EC-TYPE',
        'name_en' => 'Employee Create Test Type',
    ]);

    // Employee numbers are generated by the existing code-rule engine, which
    // requires an active rule for the Employee entity (mirrors DatabaseSeeder).
    CodeRule::query()->create([
        'entity_type' => CodeRuleEntityType::Employee->value,
        'scope_type' => null,
        'scope_id' => null,
        'name_en' => 'Employee Number',
        'prefix' => 'EMP',
        'format' => '{PREFIX}-{SEQUENCE}',
        'separator' => '-',
        'sequence_length' => 6,
        'next_number' => 1,
        'initial_sequence_number' => 1,
        'sequence_scope_strategy' => CodeRuleScopeStrategy::Auto,
        'sequence_scope_tokens' => [],
        'reset_frequency' => CodeRuleResetFrequency::Never,
        'year_format' => 'Y',
        'is_active' => true,
        'allow_manual_override' => true,
        'require_approval_for_override' => false,
        'active_scope_key' => CodeRule::buildActiveScopeKey(CodeRuleEntityType::Employee),
    ]);
});

function ecManager(): User
{
    return tap(User::factory()->create())->assignRole('EC Manager');
}

function ecViewer(): User
{
    return tap(User::factory()->create())->assignRole('EC Viewer');
}

function ecOrg(string $code, string $status = 'active'): Organization
{
    return Organization::query()->create([
        'organization_type_id' => test()->ecType->id,
        'code' => $code,
        'name_en' => 'Org '.$code,
        'status' => $status,
        'effective_from' => now()->toDateString(),
    ]);
}

function ecUnit(Organization $org, string $code, string $status = 'active'): OrganizationUnit
{
    return OrganizationUnit::query()->create([
        'organization_id' => $org->id,
        'unit_type' => 'department',
        'code' => $code,
        'name_en' => 'Unit '.$code,
        'status' => $status,
    ]);
}

function ecPosition(Organization $org, ?OrganizationUnit $unit, string $code, bool $isActive = true): Position
{
    return Position::query()->create([
        'organization_id' => $org->id,
        'organization_unit_id' => $unit?->id,
        'job_position_code' => $code,
        'title_en' => 'Position '.$code,
        'is_active' => $isActive,
        'effective_from' => now()->toDateString(),
    ]);
}

/** Occupy a position with a current, active assignment. */
function ecOccupy(Position $position, Organization $org): EmployeeAssignment
{
    $employee = Employee::query()->create([
        'employee_number' => 'EC-EMP-'.uniqid(),
        'first_name' => 'Sitting',
        'last_name' => 'Tenant',
        'full_name' => 'Sitting Tenant',
        'status' => EmployeeStatus::Active->value,
    ]);

    return EmployeeAssignment::query()->create([
        'employee_id' => $employee->id,
        'organization_id' => $org->id,
        'position_id' => $position->id,
        'assignment_status' => AssignmentStatus::Active->value,
        'effective_from' => now()->toDateString(),
        'is_current' => true,
    ]);
}

/** A minimally valid create payload. */
function ecPayload(Organization $org, array $overrides = []): array
{
    return array_merge([
        'first_name' => 'Abebe',
        'last_name' => 'Bekele',
        'status' => EmployeeStatus::Active->value,
        'organization_id' => $org->id,
        'effective_from' => now()->toDateString(),
    ], $overrides);
}

// ── Authorization ─────────────────────────────────────────────────────────

it('lets an authorized user open the employee create page', function (): void {
    ecOrg('EC-1');

    $this->actingAs(ecManager())
        ->get(route('employees.create'))
        ->assertOk()
        ->assertInertia(fn (Assert $page) => $page
            ->component('Employees/Create')
            ->has('organizations')
            ->has('organizationUnits')
            ->has('positions')
        );
});

it('forbids a user without employees.manage from opening the create page', function (): void {
    $this->actingAs(ecViewer())
        ->get(route('employees.create'))
        ->assertForbidden();
});

it('forbids a user without employees.manage from storing an employee', function (): void {
    $org = ecOrg('EC-2');

    $this->actingAs(ecViewer())
        ->post(route('employees.store'), ecPayload($org))
        ->assertForbidden();

    expect(Employee::query()->count())->toBe(0);
});

// ── Required validation ───────────────────────────────────────────────────

it('requires first name, last name, organization and effective date', function (): void {
    $this->actingAs(ecManager())
        ->post(route('employees.store'), [])
        ->assertSessionHasErrors(['first_name', 'last_name', 'organization_id', 'effective_from', 'status']);

    expect(Employee::query()->count())->toBe(0);
});

// ── Only ACTIVE structures are offered, and enforced server-side ───────────

it('does not offer inactive organizations, units or positions on the create page', function (): void {
    $activeOrg = ecOrg('EC-ACTIVE');
    $inactiveOrg = ecOrg('EC-INACTIVE', OrganizationStatus::Inactive->value);

    $activeUnit = ecUnit($activeOrg, 'EC-U-ACTIVE');
    ecUnit($activeOrg, 'EC-U-INACTIVE', OrganizationUnitStatus::Inactive->value);

    ecPosition($activeOrg, $activeUnit, 'EC-P-ACTIVE');
    ecPosition($activeOrg, $activeUnit, 'EC-P-INACTIVE', isActive: false);

    $this->actingAs(ecManager())
        ->get(route('employees.create'))
        ->assertOk()
        ->assertInertia(function (Assert $page) use ($activeOrg, $inactiveOrg): void {
            $page->component('Employees/Create');

            $orgIds = collect($page->toArray()['props']['organizations'])->pluck('id');
            expect($orgIds)->toContain($activeOrg->id)
                ->and($orgIds)->not->toContain($inactiveOrg->id);

            $unitCodes = collect($page->toArray()['props']['organizationUnits'])->pluck('code');
            expect($unitCodes)->toContain('EC-U-ACTIVE')
                ->and($unitCodes)->not->toContain('EC-U-INACTIVE');

            $positionCodes = collect($page->toArray()['props']['positions'])->pluck('job_position_code');
            expect($positionCodes)->toContain('EC-P-ACTIVE')
                ->and($positionCodes)->not->toContain('EC-P-INACTIVE');
        });
});

it('rejects an inactive organization on store', function (): void {
    $inactiveOrg = ecOrg('EC-3', OrganizationStatus::Inactive->value);

    $this->actingAs(ecManager())
        ->post(route('employees.store'), ecPayload($inactiveOrg))
        ->assertSessionHasErrors('organization_id');

    expect(Employee::query()->count())->toBe(0);
});

it('rejects an inactive organization unit on store', function (): void {
    $org = ecOrg('EC-4');
    $inactiveUnit = ecUnit($org, 'EC-U-4', OrganizationUnitStatus::Inactive->value);

    $this->actingAs(ecManager())
        ->post(route('employees.store'), ecPayload($org, ['organization_unit_id' => $inactiveUnit->id]))
        ->assertSessionHasErrors('organization_unit_id');

    expect(Employee::query()->count())->toBe(0);
});

it('rejects an inactive position on store', function (): void {
    $org = ecOrg('EC-5');
    $unit = ecUnit($org, 'EC-U-5');
    $inactivePosition = ecPosition($org, $unit, 'EC-P-5', isActive: false);

    $this->actingAs(ecManager())
        ->post(route('employees.store'), ecPayload($org, [
            'organization_unit_id' => $unit->id,
            'position_id' => $inactivePosition->id,
        ]))
        ->assertSessionHasErrors('position_id');

    expect(Employee::query()->count())->toBe(0);
});

// ── Occupied positions ────────────────────────────────────────────────────

it('does not offer an already-occupied position on the create page', function (): void {
    $org = ecOrg('EC-6');
    $unit = ecUnit($org, 'EC-U-6');
    $vacant = ecPosition($org, $unit, 'EC-P-VACANT');
    $occupied = ecPosition($org, $unit, 'EC-P-OCCUPIED');
    ecOccupy($occupied, $org);

    $this->actingAs(ecManager())
        ->get(route('employees.create'))
        ->assertOk()
        ->assertInertia(function (Assert $page) use ($vacant, $occupied): void {
            $positionIds = collect($page->toArray()['props']['positions'])->pluck('id');
            expect($positionIds)->toContain($vacant->id)
                ->and($positionIds)->not->toContain($occupied->id);
        });
});

it('rejects assigning an already-occupied position on store', function (): void {
    $org = ecOrg('EC-7');
    $unit = ecUnit($org, 'EC-U-7');
    $occupied = ecPosition($org, $unit, 'EC-P-7');
    ecOccupy($occupied, $org);

    $this->actingAs(ecManager())
        ->post(route('employees.store'), ecPayload($org, [
            'organization_unit_id' => $unit->id,
            'position_id' => $occupied->id,
        ]))
        ->assertSessionHasErrors('position_id');

    // Only the sitting tenant exists — no second employee was created.
    expect(Employee::query()->count())->toBe(1);
});

// ── Happy path + no raw ISO dates in props ────────────────────────────────

it('creates an employee in an active organization and position', function (): void {
    $org = ecOrg('EC-8');
    $unit = ecUnit($org, 'EC-U-8');
    $position = ecPosition($org, $unit, 'EC-P-8');

    $this->actingAs(ecManager())
        ->post(route('employees.store'), ecPayload($org, [
            'name_en' => 'Abebe Bekele',
            'organization_unit_id' => $unit->id,
            'position_id' => $position->id,
        ]))
        ->assertSessionHasNoErrors();

    expect(Employee::query()->where('first_name', 'Abebe')->value('name_en'))->toBe('Abebe Bekele');
});

it('renders the create page without raw ISO datetime strings in its props', function (): void {
    $org = ecOrg('EC-9');
    $unit = ecUnit($org, 'EC-U-9');
    ecPosition($org, $unit, 'EC-P-9');

    $this->actingAs(ecManager())
        ->get(route('employees.create'))
        ->assertOk()
        ->assertInertia(function (Assert $page): void {
            $props = json_encode($page->toArray()['props']);

            // e.g. 2026-07-09T14:21:00+03:00 — dates must be formatted by the
            // localized date helper, never leaked raw to the page.
            expect($props)->not->toMatch('/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/');
        });
});
