import { useLocale } from '@/hooks/useLocale';

const inputCls =
    'w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm text-gray-900 placeholder-gray-400 focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-100 dark:placeholder-slate-500';
const labelCls = 'block text-xs font-medium text-gray-600 dark:text-slate-400';

interface FormData {
    code: string;
    name_en: string;
    name_am: string;
    description_en: string;
    description_am: string;
    sort_order: number;
    is_active: boolean;
}

interface FormErrors {
    code?: string;
    name_en?: string;
    name_am?: string;
    description_en?: string;
    description_am?: string;
    sort_order?: string;
    is_active?: string;
}

interface Props {
    data: FormData;
    errors: FormErrors;
    onChange: <K extends keyof FormData>(key: K, value: FormData[K]) => void;
}

function Field({
    label,
    error,
    children,
}: {
    label: string;
    error?: string;
    children: React.ReactNode;
}) {
    return (
        <div>
            <label className={labelCls}>{label}</label>
            <div className="mt-1">{children}</div>
            {error && <p className="mt-1 text-xs text-red-600 dark:text-red-400">{error}</p>}
        </div>
    );
}

export default function OrganizationUnitTypeForm({ data, errors, onChange }: Props) {
    const { t } = useLocale();

    return (
        <div className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
                <Field label={t('organizationUnitTypes.code')} error={errors.code}>
                    <input
                        className={inputCls}
                        placeholder={t('organizationUnitTypes.codeAutoGenerated')}
                        value={data.code}
                        onChange={(e) => onChange('code', e.target.value)}
                    />
                </Field>
                <Field label={t('organizationUnitTypes.sortOrder')} error={errors.sort_order}>
                    <input
                        type="number"
                        className={inputCls}
                        value={data.sort_order}
                        onChange={(e) => onChange('sort_order', parseInt(e.target.value, 10) || 0)}
                    />
                </Field>
            </div>

            <Field label={`${t('organizationUnitTypes.nameEn')} *`} error={errors.name_en}>
                <input
                    className={inputCls}
                    value={data.name_en}
                    onChange={(e) => onChange('name_en', e.target.value)}
                    required
                />
            </Field>

            <Field label={t('organizationUnitTypes.nameAm')} error={errors.name_am}>
                <input
                    className={inputCls}
                    value={data.name_am}
                    onChange={(e) => onChange('name_am', e.target.value)}
                />
            </Field>

            <Field label={t('organizationUnitTypes.descriptionEn')} error={errors.description_en}>
                <textarea
                    className={inputCls}
                    rows={2}
                    value={data.description_en}
                    onChange={(e) => onChange('description_en', e.target.value)}
                />
            </Field>

            <Field label={t('organizationUnitTypes.descriptionAm')} error={errors.description_am}>
                <textarea
                    className={inputCls}
                    rows={2}
                    value={data.description_am}
                    onChange={(e) => onChange('description_am', e.target.value)}
                />
            </Field>

            <div className="flex items-center gap-2">
                <input
                    id="is_active"
                    type="checkbox"
                    className="h-4 w-4 rounded border-gray-300 text-blue-600 focus:ring-blue-500 dark:border-slate-600"
                    checked={data.is_active}
                    onChange={(e) => onChange('is_active', e.target.checked)}
                />
                <label htmlFor="is_active" className="text-sm text-gray-700 dark:text-slate-300">
                    {t('organizationUnitTypes.isActive')}
                </label>
            </div>
        </div>
    );
}
