import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import PageHeader from '@/Components/PageHeader';
import LocalizedDateDisplay from '@/Components/Calendar/LocalizedDateDisplay';
import { AppFilterBar, filterInputCls, formatScore, pageCls, Table, TablePanel, tdCls, thCls } from '@/Components/performance/ui';
import { RecordStatusBadge, usePick } from '@/Components/assessmentWorkspace/kit';
import { useLocale } from '@/hooks/useLocale';
import { Head, Link } from '@inertiajs/react';

type Row = { id: string; status: string; employee: { name?: string; name_en?: string; number?: string; unit?: string; unit_am?: string; position?: string; position_am?: string }; form: { name_en: string; name_am: string | null; version_no: number } | null; cycle: { code: string; name_en: string; name_am: string | null } | null; evaluators: number; raw: string | null; percentage: string | null; submitted_at: string | null };
type Props = { rows: { data: Row[]; current_page: number; last_page: number; per_page: number; from: number | null; to: number | null; total: number; path: string; prev_page_url: string | null; next_page_url: string | null }; filters: { status?: string; cycle?: string; search?: string }; cycles: { id: string; code: string; name_en: string; name_am: string | null }[] };

export default function ReviewIndex({ rows, filters, cycles }: Props) {
    const { t, locale } = useLocale(); const pick = usePick(); const person = (value: Row['employee']) => (locale === 'am' ? value.name || value.name_en : value.name_en || value.name) || '—';
    return <AuthenticatedLayout header={<PageHeader title={t('assessmentWorkspace.reviewsTitle')} description={t('assessmentWorkspace.reviewsDescription')} />}><Head title={t('assessmentWorkspace.reviewsTitle')} /><div className={pageCls}>
        <AppFilterBar routeName="assessment-reviews.index" filters={filters}><select name="status" className={filterInputCls} defaultValue={filters.status ?? 'submitted'}>{['submitted', 'assigned', 'pending_assignment', 'reviewed', 'acknowledged'].map((status) => <option key={status} value={status}>{t(`assessmentWorkspace.recordStatuses.${status}`)}</option>)}</select><select name="cycle" className={filterInputCls} defaultValue={filters.cycle ?? ''}><option value="">{t('assessmentWorkspace.filters.allCycles')}</option>{cycles.map((cycle) => <option key={cycle.id} value={cycle.id}>{pick(cycle.name_en, cycle.name_am)}</option>)}</select><input name="search" defaultValue={filters.search ?? ''} placeholder={t('assessmentWorkspace.filters.search')} className={filterInputCls} /></AppFilterBar>
        <TablePanel page={rows} empty={t('assessmentWorkspace.emptyReviews')}><Table head={<><th className={thCls}>{t('assessmentWorkspace.columns.employee')}</th><th className={thCls}>{t('assessmentWorkspace.columns.form')}</th><th className={thCls}>{t('assessmentWorkspace.columns.cycle')}</th><th className={thCls}>{t('assessmentWorkspace.columns.evaluators')}</th><th className={thCls}>{t('assessmentWorkspace.columns.raw')}</th><th className={thCls}>{t('assessmentWorkspace.columns.normalized')}</th><th className={thCls}>{t('assessmentWorkspace.columns.submittedAt')}</th><th className={thCls}><span className="sr-only">{t('assessmentWorkspace.columns.action')}</span></th></>}>{rows.data.map((row) => <tr key={row.id}><td className={tdCls}><p className="font-medium">{person(row.employee)}</p><p className="text-xs text-gray-500">{row.employee.number}</p><p className="text-xs text-gray-500">{pick(row.employee.unit, row.employee.unit_am)} · {pick(row.employee.position, row.employee.position_am)}</p></td><td className={tdCls}>{row.form ? `${pick(row.form.name_en, row.form.name_am)} · v${row.form.version_no}` : '—'}</td><td className={tdCls}>{row.cycle ? pick(row.cycle.name_en, row.cycle.name_am) : '—'}</td><td className={tdCls}>{row.evaluators}</td><td className={tdCls}>{formatScore(row.raw)}</td><td className={tdCls}>{row.percentage === null ? '—' : `${formatScore(row.percentage)}%`}</td><td className={tdCls}>{row.submitted_at ? <LocalizedDateDisplay value={row.submitted_at} withTime /> : '—'}<div className="mt-1"><RecordStatusBadge value={row.status} /></div></td><td className={`${tdCls} text-right`}><Link className="text-xs font-medium text-[color:var(--color-primary)]" href={route('assessment-reviews.show', row.id)}>{t('assessmentWorkspace.view')}</Link></td></tr>)}</Table></TablePanel>
    </div></AuthenticatedLayout>;
}
